In [1]:
import requests
from os import path
import pandas as pd

dat_files = {'raw_dat':{'url':'http://usc.data.socrata.com/api/views/u7m9-48qx/rows.csv?accessType=DOWNLOAD',
                       'filename':'Citizen_Connect_Variables__LA_.csv'},
             'census_tract_shapes':{'url':'http://usc.data.socrata.com/api/views/i8xf-cx8k/rows.csv?accessType=DOWNLOAD',
                             'filename':'la_county_tracts_from_jczq_z5ui.csv'},
             'neighborhood_shapes':{'url':'http://usc.data.socrata.com/api/views/nm6n-sgfb/rows.csv?accessType=DOWNLOAD',
                             'filename':'Neighborhoods_from_gw34_aa8i.csv'},
             'city_shapes':{'url':'http://usc.data.socrata.com/api/views/a8wh-tdhu/rows.csv?accessType=DOWNLOAD',
                             'filename':'Los_Angeles_Incorporated_Cities.csv'}
            }

def import_data(which_data):
    # available at https://ladata.myneighborhooddata.org/#!/view-data
    filepath = "../../localdata/" + which_data['filename']
    if not path.exists(filepath):
        filepath
        data_file = requests.get(which_data['url'])
        open(filepath, 'wb').write(data_file.content)
    return True

In [76]:
for key, val in dat_files.items():
    import_data(val)

In [3]:
raw_dat = pd.read_csv ('../../localdata/' + dat_files['raw_dat']['filename'])

In [46]:
bbb = raw_dat[pd.notnull(raw_dat['Latitude'])]

In [61]:
ccc = bbb[3:5]['Location 1']

In [74]:
[y[0] for y in [x.split() for x in ccc]]

['(34.12919012,', '(33.99827638,']

In [39]:
aaa = raw_dat[2:3]['Latitude']
type(aaa)

pandas.core.series.Series

In [34]:
raw_dat.loc[raw_dat['Latitude'] is not 'NaN']

KeyError: True

In [81]:
raw_dat.describe()

              Tract         Value   Denominator      Latitude     Longitude
count  2.567262e+06  2.585701e+06  2.333133e+06  27599.000000  27599.000000
mean   4.006540e+05  5.441605e+03  2.047294e+03     34.064983   -118.251313
std    2.236427e+05  5.654013e+05  2.749038e+03      0.177308      0.190471
min    1.011100e+05  0.000000e+00  0.000000e+00     33.140007   -118.855280
25%    2.094030e+05  5.000000e+00  6.630000e+02     33.958435   -118.379740
50%    4.036000e+05  6.500000e+01  1.365000e+03     34.054665   -118.269590
75%    5.510000e+05  3.570000e+02  2.799000e+03     34.151268   -118.136920
max    9.903000e+05  4.549267e+08  1.477000e+05     34.762260   -117.708130

In [8]:
list(raw_dat.columns)

['Policy Area',
 'Dataset',
 'Variable',
 'Name',
 'Date',
 'geoid',
 'Tract',
 'Neighborhood',
 'Value',
 'Denominator',
 'Denominator Description',
 'Row ID',
 'Location 1',
 'Latitude',
 'Longitude']

In [83]:
raw_dat[11911:12211]

,Policy Area,Dataset,Variable,Name,Date,geoid,Tract,Neighborhood,Value,Denominator,Denominator Description,Row ID,Location 1,Latitude,Longitude
11911,Employment & Income,Workers by Industry,Retail Trade Workers,Census Tract 4311,01/01/2013,1400000US06037431100,431100.0,Monrovia,136.0,2204.0,16+ Full Time Employed Population,Retail_Trade_Workers_2013_1400000US06037431100,"(34.13608039, -117.99720399)",NaN,NaN
11912,Employment & Income,Workers by Industry,Retail Trade Workers,Census Tract 4087.03,01/01/2017,1400000US06037408703,408703.0,Rowland Heights,287.0,2180.0,16+ Full Time Employed Population,Retail_Trade_Workers_2017_1400000US06037408703,"(33.95920897, -117.88855351)",NaN,NaN
11913,Employment & Income,Workers by Industry,"Real Estate, Rental & Leasing Workers",Census Tract 2181.10,01/01/2017,1400000US06037218110,218110.0,Arlington Heights,0.0,1351.0,16+ Full Time Employed Population,"Real_Estate,_Rental_&_Leasing_Workers_2017_140...","(34.04381696, -118.32581398)",NaN,NaN
11914,Employment & Income,Workers by Industry,Retail Trade Workers,Census Tract 2013.01,01/01/2012,1400000US06037201301,201301.0,Montecito Heights,15.0,769.0,16+ Full Time Employed Population,Retail_Trade_Workers_2012_1400000US06037201301,"(34.08822873, -118.18782041)",NaN,NaN
11915,Employment & Income,Workers by Industry,Retail Trade Workers,Census Tract 2377.20,01/01/2017,1400000US06037237720,237720.0,Vermont Knolls,117.0,807.0,16+ Full Time Employed Population,Retail_Trade_Workers_2017_1400000US06037237720,"(33.96929119, -118.28616326)",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12206,Employment & Income,Workers by Industry,"Real Estate, Rental & Leasing Workers",Census Tract 3102.02,01/01/2012,1400000US06037310202,310202.0,Burbank,0.0,1663.0,16+ Full Time Employed Population,"Real_Estate,_Rental_&_Leasing_Workers_2012_140...","(34.18806056, -118.29604589)",NaN,NaN
12207,Employment & Income,Workers by Industry,Transportation & Warehousing Workers,Census Tract 1953,01/01/2011,1400000US06037195300,195300.0,Los Feliz,58.0,1281.0,16+ Full Time Employed Population,Transportation_&_Warehousing_Workers_2011_1400...,"(34.09925542, -118.28370152)",NaN,NaN
12208,Employment & Income,Workers by Industry,Retail Trade Workers,Census Tract 2943.01,01/01/2010,1400000US06037294301,294301.0,Wilmington,40.0,597.0,16+ Full Time Employed Population,Retail_Trade_Workers_2010_1400000US06037294301,"(33.79466667, -118.27956481)",NaN,NaN
12209,Employment & Income,Workers by Industry,Transportation & Warehousing Workers,Census Tract 4013.12,01/01/2011,1400000US06037401312,401312.0,San Dimas,49.0,1565.0,16+ Full Time Employed Population,Transportation_&_Warehousing_Workers_2011_1400...,"(34.09885862, -117.8289455)",NaN,NaN
12210,Employment & Income,Workers by Industry,Retail Trade Workers,Census Tract 5421.05,01/01/2017,1400000US06037542105,542105.0,Compton,139.0,1429.0,16+ Full Time Employed Population,Retail_Trade_Workers_2017_1400000US06037542105,"(33.89321589, -118.1990772)",NaN,NaN

In [ ]:
df1.groupby(['Policy Area',
             'Dataset',
            'Variable',
            'Name',
            ]).size().reset_index().rename(columns={0:'count'})